---
default:
  interruptible: true

stages:
  - prepare
  - deploy

include:
  - local: .gitlab/ci/global.gitlab-ci.yml

review-build-cng-env:
  image: ${GITLAB_DEPENDENCY_PROXY_ADDRESS}ruby:${RUBY_VERSION}-alpine3.16
  
  stage: prepare
  
  needs:
    # precisamos desse job porque precisamos do artefato `cached-assets-hash.txt`
    - pipeline: $PARENT_PIPELINE_ID
      job: build-assets-image
      
  variables:
    BUILD_ENV: build.env
    
  before_script:
    - source ./scripts/utils.sh
    - install_gitlab_gem
    
  script:
    - 'ruby -r./scripts/trigger-build.rb -e "puts Trigger.variables_for_env_file(Trigger::CNG.new.variables)" > $BUILD_ENV'
    - echo "GITLAB_ASSETS_TAG=$(assets_image_tag)" >> $BUILD_ENV
    - ruby -e 'puts "FULL_RUBY_VERSION=#{RUBY_VERSION}"' >> build.env
    - cat $BUILD_ENV
    
  artifacts:
    reports:
      dotenv: $BUILD_ENV
      
    paths:
      - $BUILD_ENV
      
    expire_in: 7 days
    
    when: always

review-build-cng:
  stage: prepare
  
  inherit:
    variables: false
    
  variables:
    GITLAB_REF_SLUG: "${GITLAB_REF_SLUG}"
    # variáveis específicas de pipeline de cng
    
    GITLAB_VERSION: "${GITLAB_VERSION}"
    GITLAB_TAG: "${GITLAB_TAG}"
    GITLAB_ASSETS_TAG: "${GITLAB_ASSETS_TAG}"
    
    FORCE_RAILS_IMAGE_BUILDS: "${FORCE_RAILS_IMAGE_BUILDS}"
    
    CE_PIPELINE: "${CE_PIPELINE}"  # baseado em https://docs.gitlab.com/ee/ci/jobs/job_control.html#check-if-a-variable-exists
    EE_PIPELINE: "${EE_PIPELINE}"  # baseado em https://docs.gitlab.com/ee/ci/jobs/job_control.html#check-if-a-variable-exists
    
    GITLAB_ELASTICSEARCH_INDEXER_VERSION: "${GITLAB_ELASTICSEARCH_INDEXER_VERSION}"
    GITLAB_KAS_VERSION: "${GITLAB_KAS_VERSION}"
    GITLAB_METRICS_EXPORTER_VERSION: "${GITLAB_METRICS_EXPORTER_VERSION}"
    GITLAB_PAGES_VERSION: "${GITLAB_PAGES_VERSION}"
    GITLAB_SHELL_VERSION: "${GITLAB_SHELL_VERSION}"
    GITLAB_WORKHORSE_VERSION: "${GITLAB_WORKHORSE_VERSION}"
    GITALY_SERVER_VERSION: "${GITALY_SERVER_VERSION}"
    
    RUBY_VERSION: "${FULL_RUBY_VERSION}"]
    
  trigger:
    project: gitlab-org/build/CNG-mirror
    branch: $TRIGGER_BRANCH
    strategy: depend
