[semgrep]
    description = 'configuração de regras personalizadas do semgrep'
    targetdir = "/sgrules"
    validate = true

    [[semgrep.passthrough]]
        type = "git"
        value = "https://gitlab.com/gitlab-com/gl-security/appsec/sast-custom-rules.git"
        ref = "refs/heads/main"
        subdir = "appsec-pings"