[secrets]
    [[secrets.ruleset]]
        disable = true

        [secrets.ruleset.identifier]
            type = "gitleaks_rule_id"
            value = "senha em url"

    [[secrets.passthrough]]
        type = "file"

        # notar que isso deve ser gitleaks.toml
        target = "gitleaks.toml"
        value = "config/gitleaks.toml"